image: node:16.20.0

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@6.2.1
  - npm install
  - ng build
  - mkdir -p public
  - mv dist/out-tsc/* public/
  artifacts:
    paths:
    - public
  only:
  - main